quarkus.datasource.db-kind=mssql
# 2. Configura as credenciais e o URL de ligação
quarkus.datasource.username=medidata
quarkus.datasource.password=medidata
quarkus.datasource.jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=saga_fdv;encrypt=false
# 3. Configuração do Hibernate (Controla se ele altera tabelas - "none" para produção/segurança)
quarkus.hibernate-orm.database.generation=none
quarkus.datasource.db-version=12.0.0